name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y autoconf automake libtool

      - name: Generate build files
        run: ./autogen.sh && ./configure

      - name: Build
        run: make clean all
